# Generated by Django 4.1.3 on 2022-11-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_history_client_id_alter_history_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='price_per_night',
            new_name='days_spent',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='stars',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='history',
            name='single',
        ),
        migrations.RemoveField(
            model_name='history',
            name='smoking',
        ),
        migrations.AddField(
            model_name='history',
            name='review',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='history',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.users'),
        ),
        migrations.AlterField(
            model_name='history',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.users'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.room'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
