# Generated by Django 4.1.3 on 2022-11-25 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_testmod_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmod',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tmod', to=settings.AUTH_USER_MODEL),
        ),
    ]
