# Generated by Django 4.1.3 on 2022-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_testmod_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank='NONE', max_length=255),
        ),
    ]
