# Generated by Django 4.1.3 on 2022-12-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.RemoveField(
            model_name='testmod',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='history',
        ),
        migrations.DeleteModel(
            name='testmod',
        ),
    ]
